Imports System.Text
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports _3LAWMN12VW.ValidationRuleData

<TestClass()> Public Class TestApplicantID

    <TestMethod()> Public Sub TestConstruction_Default()
        Dim tstPIObj As ProcessInfo = ProcessInfo.Fetch(Nothing, Nothing)
        Dim tstAppIdObj As ApplicantID = ApplicantID.Fetch("BUY", tstPIObj, Nothing, Nothing)
        Assert.AreEqual("BUY", tstAppIdObj.ApplicantType)
        Assert.AreEqual("", tstAppIdObj.Family)
        Assert.AreEqual("", tstAppIdObj.Given)
        Assert.AreEqual("", tstAppIdObj.Middle)
        Assert.AreEqual("", tstAppIdObj.BirthDate)
        Assert.AreEqual(-1, tstAppIdObj.Age)
        Assert.AreEqual("", tstAppIdObj.DriverLicense)
        Assert.AreEqual("", tstAppIdObj.DriverLicenseExpiry)
        Assert.AreEqual("", tstAppIdObj.IssuingState)
        Assert.AreEqual("", tstAppIdObj.NationalID)
        Assert.AreEqual("", tstAppIdObj.Suffix)
    End Sub
    <TestMethod()> Public Sub TestConstruction_Aristo()
        Dim d As New Dictionary(Of String, Object)
        d.Add("BUY_LASTNAME", "PBS")
        d.Add("BUY_INITNAME", "M")
        d.Add("BUY_FIRSTNAME", "PBS")
        d.Add("BUY_BIRTHDATE", "05/01/2014")
        d.Add("BUY_AGE", 10)
        d.Add("BUY_SIN", "999-999-999")
        d.Add("BUY_DLIC_NO", "1320941250974")
        d.Add("BUY_DLIC_EXP", "06/01/2014")
        d.Add("BUY_DLIC_STATE", "MN")
        Dim tstPIObj As ProcessInfo = ProcessInfo.Fetch(Nothing, Nothing)
        Dim tstAppIdObj As ApplicantID = ApplicantID.Fetch("BUY", tstPIObj, Nothing, d)
        Assert.AreEqual("BUY", tstAppIdObj.ApplicantType)
        Assert.AreEqual("PBS", tstAppIdObj.Family)
        Assert.AreEqual("PBS", tstAppIdObj.Given)
        Assert.AreEqual("M", tstAppIdObj.Middle)
        Assert.AreEqual("", tstAppIdObj.Suffix)
        Assert.AreEqual("05/01/2014", tstAppIdObj.BirthDate)
        Assert.AreEqual(10, tstAppIdObj.Age)
        Assert.AreEqual("1320941250974", tstAppIdObj.DriverLicense)
        Assert.AreEqual("06/01/2014", tstAppIdObj.DriverLicenseExpiry)
        Assert.AreEqual("999-999-999", tstAppIdObj.NationalID)
        Assert.AreEqual("MN", tstAppIdObj.IssuingState)
    End Sub
    <TestMethod()> Public Sub TestConstruction_PreviousRun()
        Dim d As New Dictionary(Of String, Object)
        d.Add("BUY_SUFFIX", "I")
        Dim tstPIObj As ProcessInfo = ProcessInfo.Fetch(Nothing, Nothing)
        Dim tstAppIdObj As ApplicantID = ApplicantID.Fetch("BUY", tstPIObj, d, Nothing)
        Assert.AreEqual("", tstAppIdObj.Suffix) 'Both are required must be mixed.
    End Sub
    <TestMethod()> Public Sub TestConstruction_Mixed()
        Dim pd As New Dictionary(Of String, Object)
        pd.Add("BUY_LASTNAME", "SBP")
        pd.Add("BUY_INITNAME", "N")
        pd.Add("BUY_FIRSTNAME", "SBP")
        pd.Add("BUY_BIRTHDATE", "01/05/2014")
        pd.Add("BUY_AGE", 99)
        pd.Add("BUY_SUFFIX", "I")
        pd.Add("BUY_SIN", "888-888-888")
        pd.Add("BUY_DLIC_NO", "999999999")
        pd.Add("BUY_DLIC_EXP", "01/06/2014")
        pd.Add("BUY_DLIC_STATE", "NM")
        Dim d As New Dictionary(Of String, Object)
        d.Add("BUY_LASTNAME", "PBS")
        d.Add("BUY_INITNAME", "M")
        d.Add("BUY_FIRSTNAME", "PBS")
        d.Add("BUY_BIRTHDATE", "05/01/2014")
        d.Add("BUY_AGE", 10)
        d.Add("BUY_SIN", "999-999-999")
        d.Add("BUY_DLIC_NO", "1320941250974")
        d.Add("BUY_DLIC_EXP", "06/01/2014")
        d.Add("BUY_DLIC_STATE", "MN")
        Dim tstPIObj As ProcessInfo = ProcessInfo.Fetch(Nothing, Nothing)
        Dim tstAppIdObj As ApplicantID = ApplicantID.Fetch("BUY", tstPIObj, pd, d)
        Assert.AreEqual("BUY", tstAppIdObj.ApplicantType)
        Assert.AreEqual("PBS", tstAppIdObj.Family)
        Assert.AreEqual("PBS", tstAppIdObj.Given)
        Assert.AreEqual("M", tstAppIdObj.Middle)
        Assert.AreEqual("I", tstAppIdObj.Suffix)
        Assert.AreEqual("05/01/2014", tstAppIdObj.BirthDate)
        Assert.AreEqual(10, tstAppIdObj.Age)
        Assert.AreEqual("1320941250974", tstAppIdObj.DriverLicense)
        Assert.AreEqual("06/01/2014", tstAppIdObj.DriverLicenseExpiry)
        Assert.AreEqual("999-999-999", tstAppIdObj.NationalID)
        Assert.AreEqual("MN", tstAppIdObj.IssuingState)
    End Sub
End Class