Imports System.Text
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports _3LAWMN12VW
Imports _3LAWMN12VW.ValidationRuleData

<TestClass()> Public Class TestAddress

    <TestMethod()> Public Sub TestConstruction_Default()
        Dim tstPIObj As ProcessInfo = ProcessInfo.Fetch(Nothing, Nothing)
        Dim tstAppAddrObj As Address = Address.Fetch("BUY", Applicant.C_HOMEADDRESS, tstPIObj, Nothing, Nothing)
        Assert.AreEqual(Applicant.C_HOMEADDRESS, tstAppAddrObj.AddressType)
        Assert.AreEqual(True, tstAppAddrObj.SameAsHomeAddress)
        Assert.AreEqual("", tstAppAddrObj.Line1)
        Assert.AreEqual("", tstAppAddrObj.Line2)
        Assert.AreEqual("", tstAppAddrObj.City)
        Assert.AreEqual("", tstAppAddrObj.State)
        Assert.AreEqual("", tstAppAddrObj.Zip)
        Assert.AreEqual("", tstAppAddrObj.County)
    End Sub
    <TestMethod()> Public Sub TestConstructor_AristoHomeAddress()
        Dim pd As New Dictionary(Of String, Object)
        pd.Add("BUY_SAMEASHOME", True) ' Wipe Out/Ignore Garage
        pd.Add("BUY_ADDRESS", "54321 EREHWYREVE TS.")
        pd.Add("BUY_CITY", "YRAGLAC")
        pd.Add("BUY_PROV", "BA")
        pd.Add("BUY_PCODE", "J2T 4S3")
        pd.Add("BUY_COUNTY", "REVOD")
        Dim d As New Dictionary(Of String, Object)
        d.Add("BUY_ADDRESS", "12345 EVERYWHERE ST.")
        d.Add("BUY_CITY", "Calgary")
        d.Add("BUY_PROV", "Alberta")
        d.Add("BUY_PCODE", "T2J 3S4")
        d.Add("BUY_COUNTY", "DOVER")
        Dim tstPIObj As ProcessInfo = ProcessInfo.Fetch(Nothing, Nothing)
        Dim tstAppAddrObj As Address = Address.Fetch("BUY", Applicant.C_HOMEADDRESS, tstPIObj, Nothing, d)
        Assert.AreEqual(Applicant.C_HOMEADDRESS, tstAppAddrObj.AddressType)
        Assert.AreEqual(True, tstAppAddrObj.SameAsHomeAddress)
        Assert.AreEqual("12345 EVERYWHERE ST.", tstAppAddrObj.Line1, True)
        Assert.AreEqual("", tstAppAddrObj.Line2, True)
        Assert.AreEqual("Calgary", tstAppAddrObj.City, True)
        Assert.AreEqual("AB", tstAppAddrObj.State, True)
        Assert.AreEqual("T2J 3S4", tstAppAddrObj.Zip, True)
        Assert.AreEqual("DOVER", tstAppAddrObj.County, True)
    End Sub
    <TestMethod()> Public Sub TestConstructor_SecondPassGarageIgnore()
        Dim pd As New Dictionary(Of String, Object)
        pd.Add("BUY_GARAGE_SAMEASHOME", True) ' Wipe Out/Ignore Garage
        pd.Add("BUY_GARAGE_ADDRESS", "54321 EREHWYREVE TS.")
        pd.Add("BUY_GARAGE_CITY", "YRAGLAC")
        pd.Add("BUY_GARAGE_PROV", "BA")
        pd.Add("BUY_GARAGE_PCODE", "J2T 4S3")
        pd.Add("BUY_GARAGE_COUNTY", "REVOD")
        Dim d As New Dictionary(Of String, Object)
        d.Add("BUY_ADDRESS", "12345 EVERYWHERE ST.")
        d.Add("BUY_CITY", "Calgary")
        d.Add("BUY_PROV", "Alberta")
        d.Add("BUY_PCODE", "T2J 3S4")
        d.Add("BUY_COUNTY", "DOVER")
        Dim tstPIObj As ProcessInfo = ProcessInfo.Fetch(Nothing, Nothing)
        Dim tstAppAddrObj As Address = Address.Fetch("BUY", Applicant.C_GARAGEADDRESS, tstPIObj, pd, d)
        Assert.AreEqual(Applicant.C_GARAGEADDRESS, tstAppAddrObj.AddressType)
        Assert.AreEqual(True, tstAppAddrObj.SameAsHomeAddress)
        Assert.AreEqual("12345 EVERYWHERE ST.", tstAppAddrObj.Line1, True)
        Assert.AreEqual("", tstAppAddrObj.Line2, True)
        Assert.AreEqual("Calgary", tstAppAddrObj.City, True)
        Assert.AreEqual("AB", tstAppAddrObj.State, True)
        Assert.AreEqual("T2J 3S4", tstAppAddrObj.Zip, True)
        Assert.AreEqual("DOVER", tstAppAddrObj.County, True)
    End Sub
    <TestMethod()> Public Sub TestConstructor_SecondPassGarageRetain()
        Dim pd As New Dictionary(Of String, Object)
        pd.Add("BUY_GARAGE_SAMEASHOME", False) ' Wipe Out/Ignore Garage
        pd.Add("BUY_GARAGE_ADDRESS", "54321 EREHWYREVE TS.")
        pd.Add("BUY_GARAGE_CITY", "YRAGLAC")
        pd.Add("BUY_GARAGE_PROV", "BA")
        pd.Add("BUY_GARAGE_PCODE", "J2T 4S3")
        pd.Add("BUY_GARAGE_COUNTY", "REVOD")
        Dim d As New Dictionary(Of String, Object)
        d.Add("BUY_ADDRESS", "12345 EVERYWHERE ST.")
        d.Add("BUY_CITY", "Calgary")
        d.Add("BUY_PROV", "Alberta")
        d.Add("BUY_PCODE", "T2J 3S4")
        d.Add("BUY_COUNTY", "DOVER")
        Dim tstPIObj As ProcessInfo = ProcessInfo.Fetch(Nothing, Nothing)
        Dim tstAppAddrObj As Address = Address.Fetch("BUY", Applicant.C_GARAGEADDRESS, tstPIObj, pd, d)
        Assert.AreEqual(Applicant.C_GARAGEADDRESS, tstAppAddrObj.AddressType)
        Assert.AreEqual(False, tstAppAddrObj.SameAsHomeAddress)
        Assert.AreEqual("54321 EREHWYREVE TS.", tstAppAddrObj.Line1, True)
        Assert.AreEqual("", tstAppAddrObj.Line2, True)
        Assert.AreEqual("YRAGLAC", tstAppAddrObj.City, True)
        Assert.AreEqual("BA", tstAppAddrObj.State, True)
        Assert.AreEqual("J2T 4S3", tstAppAddrObj.Zip, True)
        Assert.AreEqual("REVOD", tstAppAddrObj.County, True)
    End Sub
End Class