Imports System.Text
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports VWContractValidation.ValidationLib

<TestClass()> Public Class TestApplicant

    <TestMethod()> Public Sub TestDefaultConstructor()
        Dim pRun As New Dictionary(Of String, Object)
        Dim cRun As New Dictionary(Of String, Object)
        Dim bArgs As New BaseConstructionArgs With {.PreviousRun = pRun, .CurrentRun = cRun}
        Dim aArgs As New ApplicantArgs With {.applicantType = ApplicantArgs.ApplicantTypes.BUYER1, .CurrentRun = cRun, .PreviousRun = pRun}
        Dim tst As Applicant = Applicant.Fetch(aArgs)
        Assert.AreEqual(Nothing, tst.BusinessName)
        Assert.AreEqual(String.Empty, tst.CustomerName.Family)
        Assert.AreEqual(String.Empty, tst.Addresses(Address.C_HOMEADDRESS).Line1)
        Assert.AreEqual(String.Empty, tst.Addresses(Address.C_BILLINGADDRESS).City)
        Assert.AreEqual("MN", tst.Addresses(Address.C_GARAGEADDRESS).State)
        Assert.AreEqual(String.Empty, tst.AltContact.EMail)
    End Sub
    <TestMethod()> Public Sub TestBuyerConstruction()
        Dim pRun As New Dictionary(Of String, Object) From _
            {{"DLR_NAME", "PBS SYSTEMS INC."},
             {"DLR_DBA", "Software People of Canada"},
             {"DLR_ADDR", "3131 114TH AVENUE SE"},
             {"DLR_CITY", "CALGARY"},
{"DLR_PROV", "AB"},
{"DLR_PCODE", "T2Z 3X2"},
{"DLR_PHONE", "(403) 253-6304"},
{"DLR_FAX", "(403) 255-7532"},
{"DLR_TAX", "87867 6899"},
{"DLR_COUNTRY", "US"},
{"DLR_CODE", "VCI######"},
{"BUY_CODE", "ELWOOD"},
{"BUY_FIRST", "ELWOOD"},
{"BUY_INIT", "J."},
{"BUY_LAST", "BLUES"},
{"BUY_ADDR", "1234 BLUES AVENUE"},
{"BUY_CITY", "Chicago"},
{"BUY_PROV", "IL"},
{"BUY_PCODE", "60420-3975"},
{"BUY_APT", "1234"},
{"BUY_COUNTY", "Dwight"},
{"BUY_BDTE", "08/25/1980"},
{"BUY_HOMEPHONE", "(403) 234-5678"},
{"BUY_BUSSPHONE", "(403) 123-4567"},
{"BUY_CELLPHONE", "(403) 345-6789"},
{"BUY_FAX", "(403) 456-7890"},
{"BUY_DLICENSE", "987654321"},
{"BUY_DLICENSEEXP", "11/08/2012"},
{"BUY_EMAIL", "elwoodblues@gmail.com"},
{"BUY_EMPLOYER", "Blessed Acceleration Church"},
{"BUY_LANGUAGE", "EN"},
{"BUY_OCCUPATION", "Driver"},
{"BUY_SEX", "Male"},
{"BUY_SALUTATION", "Mr"},
{"BUY_SIN", "111999888"},
{"BUY_GSTNUMBER", ""},
{"BUY_ISBUSINESS", False},
{"BUY_COMPANY", ""},
{"BUY_CUSTOM01NAME", ""},
{"BUY_CUSTOM01TYPE", ""},
{"BUY_CUSTOM01VALUE", ""},
{"BUY_CUSTOM02NAME", ""},
{"BUY_CUSTOM02TYPE", ""},
{"BUY_CUSTOM02VALUE", ""},
{"BUY_CUSTOM03NAME", ""},
{"BUY_CUSTOM03TYPE", ""},
{"BUY_CUSTOM03VALUE", ""},
{"BUY_CUSTOM04NAME", ""},
{"BUY_CUSTOM04TYPE", ""},
{"BUY_CUSTOM04VALUE", ""},
{"BUY_CUSTOM05NAME", ""},
{"BUY_CUSTOM05TYPE", ""},
{"BUY_CUSTOM05VALUE", ""},
{"BUY_CUSTOM06NAME", ""},
{"BUY_CUSTOM06TYPE", ""},
{"BUY_CUSTOM06VALUE", ""},
{"BUY_CUSTOM07NAME", ""},
{"BUY_CUSTOM07TYPE", ""},
{"BUY_CUSTOM07VALUE", ""},
{"BUY_CUSTOM08NAME", ""},
{"BUY_CUSTOM08TYPE", ""},
{"BUY_CUSTOM08VALUE", ""},
{"BUY_CUSTOM09NAME", ""},
{"BUY_CUSTOM09TYPE", ""},
{"BUY_CUSTOM09VALUE", ""},
{"BUY_CUSTOM10NAME", ""},
{"BUY_CUSTOM10TYPE", ""},
{"BUY_CUSTOM10VALUE", ""},
             {"DEAL_FCALC", 0}}
        Dim cRun As New Dictionary(Of String, Object) From {{"DLR_NAME", "PBS SYSTEMS INC."},
             {"DLR_DBA", "Software People of Canada"},
             {"DLR_ADDR", "3131 114TH AVENUE SE"},
             {"DLR_CITY", "CALGARY"},
{"DLR_PROV", "AB"},
{"DLR_PCODE", "T2Z 3X2"},
{"DLR_PHONE", "(403) 253-6304"},
{"DLR_FAX", "(403) 255-7532"},
{"DLR_TAX", "87867 6899"},
{"DLR_COUNTRY", "US"},
{"DLR_CODE", "VCI######"},
{"BUY_CODE", "ELWOOD"},
{"BUY_FIRST", "ELWOOD"},
{"BUY_INIT", "J."},
{"BUY_LAST", "BLUES"},
{"BUY_ADDR", "1234 BLUES AVENUE"},
{"BUY_CITY", "Chicago"},
{"BUY_PROV", "IL"},
{"BUY_PCODE", "60420-3975"},
{"BUY_APT", "1234"},
{"BUY_COUNTY", "Dwight"},
{"BUY_BDTE", "08/25/1980"},
{"BUY_HOMEPHONE", "(403) 234-5678"},
{"BUY_BUSSPHONE", "(403) 123-4567"},
{"BUY_CELLPHONE", "(403) 345-6789"},
{"BUY_FAX", "(403) 456-7890"},
{"BUY_DLICENSE", "987654321"},
{"BUY_DLICENSEEXP", "11/08/2012"},
{"BUY_EMAIL", "elwoodblues@gmail.com"},
{"BUY_EMPLOYER", "Blessed Acceleration Church"},
{"BUY_LANGUAGE", "EN"},
{"BUY_OCCUPATION", "Driver"},
{"BUY_SEX", "Male"},
{"BUY_SALUTATION", "Mr"},
{"BUY_SIN", "111999888"},
{"BUY_GSTNUMBER", ""},
{"BUY_ISBUSINESS", False},
{"BUY_COMPANY", ""},
{"BUY_CUSTOM01NAME", ""},
{"BUY_CUSTOM01TYPE", ""},
{"BUY_CUSTOM01VALUE", ""},
{"BUY_CUSTOM02NAME", ""},
{"BUY_CUSTOM02TYPE", ""},
{"BUY_CUSTOM02VALUE", ""},
{"BUY_CUSTOM03NAME", ""},
{"BUY_CUSTOM03TYPE", ""},
{"BUY_CUSTOM03VALUE", ""},
{"BUY_CUSTOM04NAME", ""},
{"BUY_CUSTOM04TYPE", ""},
{"BUY_CUSTOM04VALUE", ""},
{"BUY_CUSTOM05NAME", ""},
{"BUY_CUSTOM05TYPE", ""},
{"BUY_CUSTOM05VALUE", ""},
{"BUY_CUSTOM06NAME", ""},
{"BUY_CUSTOM06TYPE", ""},
{"BUY_CUSTOM06VALUE", ""},
{"BUY_CUSTOM07NAME", ""},
{"BUY_CUSTOM07TYPE", ""},
{"BUY_CUSTOM07VALUE", ""},
{"BUY_CUSTOM08NAME", ""},
{"BUY_CUSTOM08TYPE", ""},
{"BUY_CUSTOM08VALUE", ""},
{"BUY_CUSTOM09NAME", ""},
{"BUY_CUSTOM09TYPE", ""},
{"BUY_CUSTOM09VALUE", ""},
{"BUY_CUSTOM10NAME", ""},
{"BUY_CUSTOM10TYPE", ""},
{"BUY_CUSTOM10VALUE", ""},
             {"DEAL_FCALC", 0}}
        Dim bArgs As New BaseConstructionArgs With {.PreviousRun = pRun, .CurrentRun = cRun}
        Dim aArgs As New ApplicantArgs With {.applicantType = ApplicantArgs.ApplicantTypes.BUYER1, .GlobalProperty = ProcessInfo.Fetch(bArgs), .CurrentRun = cRun, .PreviousRun = pRun}
        Dim tst As Applicant = Applicant.Fetch(aArgs)
        Assert.AreEqual(Nothing, tst.BusinessName)
        Assert.AreEqual("Blues", tst.CustomerName.Family, True)
        Assert.AreEqual("1234 BLUES AVENUE", tst.Addresses(Address.C_HOMEADDRESS).Line1, True)
        Assert.AreEqual("Chicago", tst.Addresses(Address.C_BILLINGADDRESS).City, True)
        Assert.AreEqual("IL", tst.Addresses(Address.C_GARAGEADDRESS).State, True)
        Assert.AreEqual("elwoodblues@gmail.com", tst.AltContact.EMail, True)
    End Sub
    <TestMethod()> Public Sub TestCobuyerConstruction()
        Dim pRun As New Dictionary(Of String, Object) From _
            {{"DLR_NAME", "PBS SYSTEMS INC."},
{"DLR_DBA", "Software People of Canada"},
{"DLR_ADDR", "3131 114TH AVENUE SE"},
{"DLR_CITY", "CALGARY"},
{"DLR_PROV", "AB"},
{"DLR_PCODE", "T2Z 3X2"},
{"DLR_PHONE", "(403) 253-6304"},
{"DLR_FAX", "(403) 255-7532"},
{"DLR_TAX", "87867 6899"},
{"DLR_COUNTRY", "Canada"},
{"DLR_CODE", "GST123456  DLR34627  FMC#####"},
            {"COBUYER1_CODE", "Hello"},
{"COBUYER1_FIRST", "Morty"},
{"COBUYER1_INIT", "M"},
{"COBUYER1_LAST", "Mandagoria"},
{"COBUYER1_ADDR", "4321 EVERYWHERE ST."},
{"COBUYER1_CITY", "CALGARY"},
{"COBUYER1_PROV", "ALBERTA"},
{"COBUYER1_PCODE", "T2J 3S5"},
{"COBUYER1_BILLING_SAMEASHOME", False},
{"COBUYER1_BILLING_ADDR", "4321 EVERYWHERE ST."},
{"COBUYER1_BILLING_CITY", "WINNIPEG"},
{"COBUYER1_BILLING_PROV", "MANITOBA"},
{"COBUYER1_BILLING_PCODE", "T2J 3S5"},
{"COBUYER1_GARAGE_SAMEASHOME", False},
{"COBUYER1_GARAGE_ADDR", "4321 EVERYWHERE ST."},
{"COBUYER1_GARAGE_CITY", "EDMONTON"},
{"COBUYER1_GARAGE_PROV", "ALBERTA"},
{"COBUYER1_GARAGE_PCODE", "T2J 3S5"},
{"COBUYER1_APT", "409"},
{"COBUYER1_COUNTY", ""},
{"COBUYER1_BDTE", "09/01/1990"},
{"COBUYER1_HOMEPHONE", "(403) 271-7333"},
{"COBUYER1_BUSSPHONE", "(999) 999-9999"},
{"COBUYER1_CELLPHONE", "(888) 888-8888"},
{"COBUYER1_FAX", "(777) 777-7777"},
{"COBUYER1_DLICENSE", "98475246"},
{"COBUYER1_DLICENSEEXP", "09/01/2015"},
{"COBUYER1_EMAIL", "Mandy@gmail.com"},
{"COBUYER1_EMPLOYER", ""},
{"COBUYER1_LANGUAGE", "en-US"},
{"COBUYER1_OCCUPATION", ""},
{"COBUYER1_SEX", ""},
{"COBUYER1_SALUTATION", ""},
{"COBUYER1_SIN", "999-888-666"},
{"COBUYER1_GSTNUMBER", "2391875"},
{"COBUYER1_ISBUSINESS", False},
{"COBUYER1_COMPANY", ""},
{"COBUYER1_CUSTOM01NAME", ""},
{"COBUYER1_CUSTOM01TYPE", ""},
{"COBUYER1_CUSTOM01VALUE", ""},
{"COBUYER1_CUSTOM02NAME", ""},
{"COBUYER1_CUSTOM02TYPE", ""},
{"COBUYER1_CUSTOM02VALUE", ""},
{"COBUYER1_CUSTOM03NAME", ""},
{"COBUYER1_CUSTOM03TYPE", ""},
{"COBUYER1_CUSTOM03VALUE", ""},
{"COBUYER1_CUSTOM04NAME", ""},
{"COBUYER1_CUSTOM04TYPE", ""},
{"COBUYER1_CUSTOM04VALUE", ""},
{"COBUYER1_CUSTOM05NAME", ""},
{"COBUYER1_CUSTOM05TYPE", ""},
{"COBUYER1_CUSTOM05VALUE", ""},
{"COBUYER1_CUSTOM06NAME", ""},
{"COBUYER1_CUSTOM06TYPE", ""},
{"COBUYER1_CUSTOM06VALUE", ""},
{"COBUYER1_CUSTOM07NAME", ""},
{"COBUYER1_CUSTOM07TYPE", ""},
{"COBUYER1_CUSTOM07VALUE", ""},
{"COBUYER1_CUSTOM08NAME", ""},
{"COBUYER1_CUSTOM08TYPE", ""},
{"COBUYER1_CUSTOM08VALUE", ""},
{"COBUYER1_CUSTOM09NAME", ""},
{"COBUYER1_CUSTOM09TYPE", ""},
{"COBUYER1_CUSTOM09VALUE", ""},
{"COBUYER1_CUSTOM10NAME", ""},
{"COBUYER1_CUSTOM10TYPE", ""},
{"COBUYER1_CUSTOM10VALUE", ""}}
        Dim cRun As New Dictionary(Of String, Object) From _
            {{"DLR_NAME", "PBS SYSTEMS INC."},
{"DLR_DBA", "Software People of Canada"},
{"DLR_ADDR", "3131 114TH AVENUE SE"},
{"DLR_CITY", "CALGARY"},
{"DLR_PROV", "AB"},
{"DLR_PCODE", "T2Z 3X2"},
{"DLR_PHONE", "(403) 253-6304"},
{"DLR_FAX", "(403) 255-7532"},
{"DLR_TAX", "87867 6899"},
{"DLR_COUNTRY", "Canada"},
{"DLR_CODE", "GST123456  DLR34627  FMC#####"},
{"COBUYER1_CODE", "Hello"},
{"COBUYER1_FIRST", "Morty"},
{"COBUYER1_INIT", "M"},
{"COBUYER1_LAST", "Mandagoria"},
{"COBUYER1_ADDR", "4321 EVERYWHERE ST."},
{"COBUYER1_CITY", "CALGARY"},
{"COBUYER1_PROV", "ALBERTA"},
{"COBUYER1_PCODE", "T2J 3S5"},
{"COBUYER1_BILLING_SAMEASHOME", False},
{"COBUYER1_BILLING_ADDR", "4321 EVERYWHERE ST."},
{"COBUYER1_BILLING_CITY", "WINNIPEG"},
{"COBUYER1_BILLING_PROV", "MANITOBA"},
{"COBUYER1_BILLING_PCODE", "T2J 3S5"},
{"COBUYER1_GARAGE_SAMEASHOME", False},
{"COBUYER1_GARAGE_ADDR", "999 EVERYWHERE ST."},
{"COBUYER1_GARAGE_CITY", "EDMONTON"},
{"COBUYER1_GARAGE_PROV", "ALBERTA"},
{"COBUYER1_GARAGE_PCODE", "T2J 3S5"},
{"COBUYER1_APT", "409"},
{"COBUYER1_COUNTY", ""},
{"COBUYER1_BDTE", "09/01/1990"},
{"COBUYER1_HOMEPHONE", "(403) 271-7333"},
{"COBUYER1_BUSSPHONE", "(999) 999-9999"},
{"COBUYER1_CELLPHONE", "(888) 888-8888"},
{"COBUYER1_FAX", "(777) 777-7777"},
{"COBUYER1_DLICENSE", "98475246"},
{"COBUYER1_DLICENSEEXP", "09/01/2015"},
{"COBUYER1_EMAIL", "Mandy@gmail.com"},
{"COBUYER1_EMPLOYER", ""},
{"COBUYER1_LANGUAGE", "en-US"},
{"COBUYER1_OCCUPATION", ""},
{"COBUYER1_SEX", ""},
{"COBUYER1_SALUTATION", ""},
{"COBUYER1_SIN", "999-888-666"},
{"COBUYER1_GSTNUMBER", "2391875"},
{"COBUYER1_ISBUSINESS", False},
{"COBUYER1_COMPANY", ""},
{"COBUYER1_CUSTOM01NAME", ""},
{"COBUYER1_CUSTOM01TYPE", ""},
{"COBUYER1_CUSTOM01VALUE", ""},
{"COBUYER1_CUSTOM02NAME", ""},
{"COBUYER1_CUSTOM02TYPE", ""},
{"COBUYER1_CUSTOM02VALUE", ""},
{"COBUYER1_CUSTOM03NAME", ""},
{"COBUYER1_CUSTOM03TYPE", ""},
{"COBUYER1_CUSTOM03VALUE", ""},
{"COBUYER1_CUSTOM04NAME", ""},
{"COBUYER1_CUSTOM04TYPE", ""},
{"COBUYER1_CUSTOM04VALUE", ""},
{"COBUYER1_CUSTOM05NAME", ""},
{"COBUYER1_CUSTOM05TYPE", ""},
{"COBUYER1_CUSTOM05VALUE", ""},
{"COBUYER1_CUSTOM06NAME", ""},
{"COBUYER1_CUSTOM06TYPE", ""},
{"COBUYER1_CUSTOM06VALUE", ""},
{"COBUYER1_CUSTOM07NAME", ""},
{"COBUYER1_CUSTOM07TYPE", ""},
{"COBUYER1_CUSTOM07VALUE", ""},
{"COBUYER1_CUSTOM08NAME", ""},
{"COBUYER1_CUSTOM08TYPE", ""},
{"COBUYER1_CUSTOM08VALUE", ""},
{"COBUYER1_CUSTOM09NAME", ""},
{"COBUYER1_CUSTOM09TYPE", ""},
{"COBUYER1_CUSTOM09VALUE", ""},
{"COBUYER1_CUSTOM10NAME", ""},
{"COBUYER1_CUSTOM10TYPE", ""},
{"COBUYER1_CUSTOM10VALUE", ""}}
        Dim bArgs As New BaseConstructionArgs With {.PreviousRun = pRun, .CurrentRun = cRun}
        Dim aArgs As New ApplicantArgs With {.applicantType = ApplicantArgs.ApplicantTypes.BUYER2, .CurrentRun = cRun, .PreviousRun = pRun}
        Dim tst As Applicant = Applicant.Fetch(aArgs)
        Assert.AreEqual(Nothing, tst.BusinessName)
        Assert.AreEqual("Mandagoria", tst.CustomerName.Family)
        Assert.AreEqual("4321 EVERYWHERE ST.", tst.Addresses(Address.C_HOMEADDRESS).Line1)
        Assert.AreEqual("Mandy@gmail.com", tst.AltContact.EMail)
    End Sub
End Class